INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, ressis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(50, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', 'None', '1 Colorless', 47, 1, 6, 1),
(70, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', 'None', '2 Colorless', 19, 1, 6, 2),
(60, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'None', '1 Colorless', 50, 1, 5, 1),
(70, 'Haunter', 'Gas Pokémon', 'Nightmare', '10', 'Psychic', 'None', '1 Colorless', 29, 1, 5, 2),
(80, 'Gengar', 'Shadow Pokémon', 'Dark Mind', '30', 'Psychic', 'None', '3 Colorless', 27, 1, 5, 3),
(60, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', 'None', '1 Colorless', 43, 1, 5, 1),
(70, 'Kadabra', 'Psi Pokémon', 'Recover', '—', 'Psychic', 'None', '2 Colorless', 32, 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', 'None', '3 Colorless', 1, 1, 5, 3),
(50, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'Steel', '1 Colorless', 62, 1, 4, 1),
(70, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'Steel', '2 Colorless', 9, 1, 4, 2),

(60, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', 'None', '1 Colorless', 58, 2, 3, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', 'None', '2 Colorless', 21, 2, 3, 2),
(90, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', 'None', '2 Colorless', 13, 2, 3, 3),
(60, 'Exeggcute', 'Egg Pokémon', 'Hypnosis', '—', 'Fire', 'None', '1 Colorless', 52, 2, 3, 1),
(80, 'Exeggutor', 'Coconut Pokémon', 'Stomp', '20+', 'Fire', 'None', '3 Colorless', 2, 2, 3, 2),
(70, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', 'None', '1 Colorless', 60, 2, 3, 1),
(80, 'Parasect', 'Mushroom Pokémon', 'Spore', '—', 'Fire', 'None', '2 Colorless', 24, 2, 3, 2),
(90, 'Victreebel', 'Flycatcher Pokémon', 'Acid', '20', 'Fire', 'None', '2 Colorless', 14, 2, 3, 3),
(70, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Electric', 'Fighting', '1 Colorless', 53, 2, 11, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Electric', 'Fighting', '2 Colorless', 19, 2, 11, 2),

(60, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Electric', 'Fighting', '1 Colorless', 57, 3, 6, 1),
(70, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Electric', 'Fighting', '2 Colorless', 24, 3, 6, 2),
(80, 'Grimer', 'Sludge Pokémon', 'Poison Gas', '10', 'Psychic', 'None', '1 Colorless', 48, 3, 6, 1),
(90, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '2 Colorless', 13, 3, 6, 2),
(100, 'Ditto', 'Transform Pokémon', 'Transform', '—', 'Fighting', 'None', '1 Colorless', 18, 3, 11, 1),
(70, 'Seel', 'Sea Lion Pokémon', 'Headbutt', '10', 'Electric', 'None', '1 Colorless', 54, 3, 2, 1),
(90, 'Dewgong', 'Sea Lion Pokémon', 'Aurora Beam', '50', 'Electric', 'None', '3 Colorless', 25, 3, 2, 2),
(80, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', 'None', '1 Colorless', 55, 3, 2, 1),
(90, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Electric', 'None', '2 Colorless', 22, 3, 2, 2),
(100, 'Dragonite', 'Dragon Pokémon', 'Slam', '40x', 'Ice', 'None', '3 Colorless', 4, 3, 9, 3);
